# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a06ae09a2ca7acaf7abc4a3588ac937af030fecc210b5eb6ccd01016539a1f96c40652a54f17734704d5fc9b4150d4943a43d6baad8a309d7660031cc70053da

test:
  secret_key_base: 685a77f0bdfc7cc55dfd7e8a1795fe62d7f8adf53947469bc1c8016927c7cb6e48c623d215318c9ad43f23b52c2e00727af732e860f3177090e0be5fcfd21726

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
